version: "3.8"
services:
  # Nginx servers
  nginx-backend:
    image: nginx
    container_name: gestion-estudiantes-nginx-backend-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - gestion-estudiantes-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3
  nginx-frontend:
    image: nginx
    container_name: gestion-estudiantes-nginx-frontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - gestion-estudiantes-frontend-network
    depends_on:
      - react1
      - react2
      - react3
  mysql:
    container_name: gestion-estudiantes-mysql-container
    image: mysql:latest  # Change version if needed
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set a strong password
      MYSQL_DATABASE: default  # Database name
    ports:
      - 3306:3306
    networks:
      - gestion-estudiantes-backend-network
  spring1:
    container_name: gestion-estudiantes-backend-container-1
    image: ivanguajardo13/pep1
    ports:
      - 8091:8090
    environment:
      DB_HOST: tingeso1
      DB_PORT: 3306
      DB_USERNAME: root  # Update if your backend uses a different user
      DB_PASSWORD: default  # Update password accordingly
    networks:
      - gestion-estudiantes-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
  spring2:
    container_name: gestion-estudiantes-backend-container-2
    image: ivanguajardo13/pep1
    ports:
      - 8092:8090
    environment:
      DB_HOST: tingeso1
      DB_PORT: 3306
      DB_USERNAME: root  # Update if your backend uses a different user
      DB_PASSWORD: default  # Update password accordingly
    networks:
      - gestion-estudiantes-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
  spring3:
    container_name: gestion-estudiantes-backend-container-3
    image: ivanguajardo13/pep1
    ports:
      - 8093:8090
    environment:
      DB_HOST: tingeso1
      DB_PORT: 3306
      DB_USERNAME: root  # Update if your backend uses a different user
      DB_PASSWORD: root_password  # Update password accordingly
    networks:
      - gestion-estudiantes-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
  react1:
    container_name: gestion-estudiantes-frontend-container-1
    image: ivanguajardo13/pep1frontend
    ports:
      - 3001:3000
    networks:
      - gestion-estudiantes-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react2:
    container_name: gestion-estudiantes-frontend-container-2
    image: ivanguajardo13/pep1frontend
    ports:
      - 3002:3000
    networks:
      - gestion-estudiantes-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: gestion-estudiantes-frontend-container-3
    image: ivanguajardo13/pep1frontend
    ports:
      - 3003:3000
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  gestion-estudiantes-postgres-volume:
networks:
  gestion-estudiantes-frontend-network:
  gestion-estudiantes-backend-network: